
spring:
  mail:
    host: smtp.gmail.com
    username: pattytester01@gmail.com
    password: dxlxnoengsnxyofd
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true